export const CATEGORIES='CATEGORIES';
export const QUESTIONS='QUESTIONS';
export const ANSWER_LIST_SELECTED='ANSWER_LIST_SELECTED';
export const ANSWER_LIST_SUCCESS='ANSWER_LIST_SUCCESS';
export const RESET_STATE = "RESET_STATE";